### ISSUE TITLE
Portal Catagories Hierarchy is confusing 

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#12]
From User Surveys - Under the "Categories" banner, there are 64 lines of information. The only thing allowing this info to be broken up is the use of indention. If possible, it would be nice to use bold, color, or rectangle fill to break these up. It would make scanning the hierarchy a lot easier on the eye. To support this, it took me ~15 seconds to find the category "Oceans", when it should really take me 1 to 5 seconds... The most awesomest thing would be to add a simple icon to the left of each category (e.g . Economy has a dollar sign icon, infrastructure has a road icon, population has a person icon, etc.). The category browsing is a little buggy.

**Comment by fishytodd** [comment]
From User Surveys - The category browsing is a little buggy. For example, when searching for wave energy, I'm presented with a category "Ecosystems And Functions", and a subcategory under that called "Species and Habitat Biodiversity". When I click the subcategory, both the category and subcategory are checked (this is fine). However, when I uncheck the category, I'd expect the subcategory to become unchecked as well...This does not occur. The buggiest part is when I uncheck the subcategory, the category becomes checked again. This definitely shouldn't happen.

**Comment by tchaddad** [comment]
These are 2 separate issues - the first item above is an enhancement request, while the second item sounds like it could be a bug (requires some testing to confirm). Do  you want to split them up Todd, or should I?

**Comment by fishytodd** [comment]
Category check box bug moved to ticket https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/19

**Comment by twelch** [comment]
I think 1-5 seconds to find something in a list this long is unrealistic but point taken.  There is room for improvement by distinguishing levels better as described.  

Icons sound good  but they will potentially clutter a UI that already has checkboxes and it's not always easy to find meaningful icons for every category, even the top-level one.  Something to consider though

**Comment by twelch** [comment]
I made some initial improvements using font-size and spacing.  Ready for review. https://github.com/twelch/wc-data-registry/commit/caa13c8c4f64d0db1db05112bda8090d8b884198
