### ISSUE TITLE
Info Button modifications

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#13]
From User Survey - The i (information hover icon) indicates that the link should be pointing to an informational webpage; perhaps the link should be disabled for records that don't have a page to point to... Also, the zip file contains a shapefile, which I feel is what many (most?) people would be looking for in the first place. Perhaps that should be mentioned in the info hover icon, though I suppose it is pretty intuitive.

**Comment by tchaddad** [comment]
This is a Bug that was introduced by adding the OPEN tag indiscriminately.  Original issue is here: Ecotrust/wc-data-registry#123

**Comment by tchaddad** [comment]
Regarding the ZIP file part of this comment - there is nothing we can do to warn users about what is inside a ZIP file, as we don't know ourselves. All we know is that these metadata URLs lead to ZIP files that are associated with the records.

**Comment by tchaddad** [comment]
Aside from the suggestion to change the "hover text" on ZIP links to explain that any type of data might be inside the ZIP file, I think this item is closeable @fishytodd. How do you want to proceed?
