### ISSUE TITLE
Portal Categories numbers unclear, misleading

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#14]
From User Surveys - Actually, I got confused. Before I clicked on Oceans it said there were 196 Ocean records and 2 Bathymetry records. I clicked on Oceans and got 196 results but Bathymetry changed from 2 to 1. So, I clicked on it expecting to see 1 dataset. Instead I got 44 datasets. I clearly don't understand how the numbers are being generated. There might not be a problem, but it makes me wonder if I'g getting all the results I'm looking for. Maybe we should have an explanation for the numbers after the category name...

**Comment by fishytodd** [comment]
We have Internet Explorer 8, and I found it awkward that check marks did not show up when I selected a category, and that removing the filter was a little box with no description. Maybe that is due to our old version of IE. When I changed to Chrome it was better, but I would prefer something like Group Layers in ArcMap so you can always see your options regardless of what is selected at the time. When I first opened it Oceans = 56 layers and Bathymetry = 2 layers. I clicked on bathymetry and Oceans = 9 and Bathymetry = 1. I don't understand why these numbers would change.

**Comment by tchaddad** [comment]
More detailed description of the Oceans issue above is now posted here: https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/19

Second comment above may be a different issue (unclear - may also be satisfied by documentation).

**Comment by tchaddad** [comment]
Like #19 I think this issue is now resolved.
