### ISSUE TITLE
Resources per results page

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#17]
From User Surveys - Recommend that the default results view be greater than 5 per page, and add the results page selector and "show per page" option at the bottom of the page too.

**Comment by tchaddad** [comment]
This is a straight up UI enhancement request. Default can be easily changed already, and the the 'show per page' is a good suggestion.

**Comment by twelch** [comment]
Ready for review. Default set to 10 and paging/dropdown now on bottom of the page as well. See pull request - https://github.com/Ecotrust/wc-data-registry/pull/147
