### ISSUE TITLE
WMS links confusing

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#18]
I had some trouble with the WMS links I tried.  For example clicking on the OR TSP Plan WMS lands here:
http://www.coastalatlas.net/services/wms/getmap/?TSP_PartFive_PlanMap_index_DLCD_2013

**Comment by tchaddad** [comment]
The link functions for me - sounds like we need to create some documentation for folks that are curious about WMS
