### ISSUE TITLE
ISO-2 records not detecting ESRI REST links

### ISSUE THREAD

**Issue by tchaddad** [WCGA/West-Coast-Ocean-Data-Portal#21]
From OSU Active Tectonics Lab, need to confirm this bug and add example records here so that we can test and resolve.

**Comment by fishytodd** [comment]
example record
http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={A3299765-3FE0-4421-8FDD-D2ABE8D1E3C6}

**Comment by tchaddad** [comment]
This bug may be solved by implementing the "OR" logic for the Geoportal XSLT described in #7

**Comment by tchaddad** [comment]
We will have to test this with some known ISO-2 records that have ESRI-REST service links, but I believe the fix that we just pushed to the Dev server should have taken care of this one.

@fishytodd - can you re-harvest the records from 'OSU Active Tectonics Laboratory' so that we can test if the REST urls are being correctly detected now?

**Comment by tchaddad** [comment]
Technically 'OSU Active Tectonics Laboratory' os now serviving regular ISO records, but I still think the fix was included in the files we pushed today, so a re-harvest is in order for testing...
