### ISSUE TITLE
NOAA records display facets

### ISSUE THREAD

**Issue by tchaddad** [WCGA/West-Coast-Ocean-Data-Portal#22]
This is a UI simplification suggestion and question:

It feels like we should group NOAA data sources with labels that reflect the part of NOAA that the data is coming from, rather than the data set or project name. 

Can we revisit the NOAA facet labels to see if simplification is possible? Would love to avoid line wrapping if possible.

**Comment by fishytodd** [comment]
I wasn't aware of this issue, do you know if there is a specific example I can take a look at?

**Comment by tchaddad** [comment]
It's not a bug, just a suggestion for label simplification

NOAA CCAP is an example of line wrapping (one of several), and it is an extremely specific product name rather than a program or office of NOAA. 

I was just wondering if there was a simpler higher level label that we could use to be more accurate. For example are the records coming from digital coast? Isn't digital coast an initiative of the NOS?

NOAA NOS may be too high level, but Digital Coast may not be

It may not be possible, but I thought we should consider something like this as part of the UI clean up recommendation. Avoiding wrapping sounds minor, but will lead to a cleaner looking UI, even if nothing else is changed.

**Comment by tchaddad** [comment]
While we're at it, we could shorted other sources to minimize wrapping, e.g.:
- BOEM - Pacific Region

In general menus are exactly the kind of places where acronyms are appropriate. We can spell out source names elsewhere (like on the http://wcga-vm01.sdsc.edu/contributors/ page)

**Comment by fishytodd** [comment]
Yes we can do this for certain contributors. I think we might have trouble regrouping the long noaa records as they are coming from specific WAFs. I will make some changes and report back.

**Comment by tchaddad** [comment]
Yeah - I understand about the different WAFs. It would be great to standardize labels where we are able, for example a pattern like:

NOAA - Program Office Acronym - Project Acronym

or something like that, so that sources cluster together in the list, even if projects are separated into different WAFs.

**Comment by tchaddad** [comment]
Looks like this one was dealt with sufficiently, so I'm calling it closable. Only remaining comment I have is that we use punctuation consistently from here on out.

So for example we should use "-" or ":" as a separator, not both (see BOEM source and NOAA Economics source for examples).
