### ISSUE TITLE
Portal Contributors list alphabetized and numbers corrected

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#24]
Moved nanoos and corrected numbers for several of contributor on Explore.html.

Needs to be pushed to production.

**Comment by emiliom** [comment]
@fishytodd, I don't see these changes on the staging WCODP, online. Maybe Jekyll didn't kick in?

Since these changes stem from my email comments (I think), I'll paste them here, for full reference. Please note also the changes to URL's for NANOOS and West Coast IOOS, since you didn't mention them in the issue description.

> On the Contributors page (http://wcga-vm01.sdsc.edu/contributors/), please fix the NANOOS link (to http://www.nanoos.org). Also, shouldn't NANOOS be listed alphabetically as all other contributors, rather than the way it currently seems to be grouped next to CeNCOOS? If all other records are listed alphabetically, there should be no exceptions. Currently they're "mostly" alphabetical, with some small creative license.
> 
> While on that topic, the link for "West Coast IOOS" currently points to the IOOS home page, which is far broader. How about changing it to this IOOS page:
> http://www.ioos.noaa.gov/regions/westcoast_mou.html
> It's the best I can think of.

Thanks!

**Comment by fishytodd** [comment]
Changes were made but I hadn't restarted jekyll. Made suggested URL
changes. Should be ready to push to production.

On Fri, Jan 9, 2015 at 8:49 AM, Emilio Mayorga notifications@github.com
wrote:

> @fishytodd https://github.com/fishytodd, I don't see these changes on
> the staging WCODP, online. Maybe Jekyll didn't kick in?
> 
> Since these changes stem from my email comments (I think), I'll paste them
> here, for full reference. Please note also the changes to URL's for NANOOS
> and West Coast IOOS, since you didn't mention them in the issue description.
> 
> On the Contributors page (http://wcga-vm01.sdsc.edu/contributors/),
> please fix the NANOOS link (to http://www.nanoos.org). Also, shouldn't
> NANOOS be listed alphabetically as all other contributors, rather than the
> way it currently seems to be grouped next to CeNCOOS? If all other records
> are listed alphabetically, there should be no exceptions. Currently they're
> "mostly" alphabetical, with some small creative license.
> 
> While on that topic, the link for "West Coast IOOS" currently points to
> the IOOS home page, which is far broader. How about changing it to this
> IOOS page:
> http://www.ioos.noaa.gov/regions/westcoast_mou.html
> It's the best I can think of.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/24#issuecomment-69361731
> .

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by emiliom** [comment]
Now I see the changes. Thanks.
