### ISSUE TITLE
link types Solr facet implemented in UI

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#29]
Enhancement to implement WAR package from ESRI in UI to display link type facets. Related to https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/7

**Comment by tchaddad** [comment]
Once this is implemented https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/7 will quickly become a high priority because it causes incorrect numbers for both ESRI REST and WMS.

**Comment by fishytodd** [comment]
When we read #29, we interpret it as just installing the WAR package.  A couple questions then to help with design considerations (and I apologize if some of these seem very basic.  I don't think about this stuff regularly enough to be completely confident):
What specifically are link type facets?
They are a filter for "Data Formats" that are contained within metadata records. I.e.  Solr creates an index that shows there are 4 ESRI REST services, 3 OGC WMS services, 2 ZIP, 1 CSV, etc... A user interested in just the records with WMS will click that filter and return just the results with WMS links present in the record. Just like the "Source", "Issue" and "Category" facets we currently expose through the Catalog UI
How would you imagine link type facets being usefully displayed?  Do you have any examples you have seen that you liked?
I imagine the link types facet being exposed similar to the Issue, category, and source filters - on the left hand side of the results page.  It should be expandable just like the other facet filters. The link types facet should be its own filter inserted in between the "issues" and "sources"
Where would they be usefully displayed in the context of the current catalog design so as to be most useful to visitors?  On the left side?  Do you see them being organized under their own label or nested within one of the existing labels?  If so, which?
 I imagine the link types facet being exposed similar to the Issue, category, and source filters - on the left hand side of the results page.  It should be expandable just like the other facet filters. The link types facet should be its own filter inserted in between the "issues" and "sources". We should call it "Data Formats" if possible. 
How many link types are there (not that this is a design constraint necessarily but just so we know what we are looking for)?
Currently it indexes on about 5 link types. We anticipate expanding this once we get it working to have at most 10.  This is where work on the #7 issue will come in. 

If you have any sketches that you have been thinking about, that might be helpful too so that we can catch up with where you are in your thinking.  I may have more questions after we understand these.  I do apologize.  We did not read this ticket as a design improvement ticket but as a package implementation ticket - two very different approaches on time as well.

I don't have any sketches, but I really want it to replicate  the current way that "Issues" is displayed. No hierarchy just a list of link types and the ability to click one and filter the results list.
