### ISSUE TITLE
Allow viewing / display of ISO-2 records in Geoportal UI

### ISSUE THREAD

**Issue by tchaddad** [WCGA/West-Coast-Ocean-Data-Portal#33]
Our installation of Geoportal on production is missing 2 key XSLT files allowing the parsing and display of ISO-2 records for access in the UI. This is not related to record harvest, just to display from the Geoportal database.

the missing files need to be placed in the following path on production:

> ```
>  /gpt/metadata/iso/
> ```

The files themselves can be found here:
- [apiso-2-summary.xslt](https://github.com/Esri/geoportal-server/blob/master/geoportal/src/gpt/metadata/iso/apiso-2-summary.xslt)
- [apiso-2-brief.xslt](https://github.com/Esri/geoportal-server/blob/master/geoportal/src/gpt/metadata/iso/apiso-2-brief.xslt)

**Comment by tchaddad** [comment]
This fixes the Geoportal error of 

> "Unable to return the document associated with the supplied identifier.” 

when trying to access an ISO-2 record from the Geoportal database that has already been harvested and successfully validated.

Note that the records in question must also be set as "Approved" in the Geoportal back end for the records to be accessible to outside users.

**Comment by fishytodd** [comment]
Moved the files to production and re tested the ISO-2 records. They are now properly showing up except for teh few bugs we have noted elsewhere. Thanks TH for pointing out those two missing files.
