### ISSUE TITLE
Multiple originators not being displayed

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#36]
For example:
http://wcga-vm01.sdsc.edu/discover/#?text=PMEP

The FGDC metadata have multiple originators, but only the last one is being displayed on the portal.  See for example:
http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={CBF56083-144F-404E-9A58-E149ED4ED3A4}

**Comment by tchaddad** [comment]
@twelch is this possibly another one similar to #27 and #38 (multiple places to look for info)?

There is a definite difference in that the place this info is supposed to show up is not on the far right, but rather in the "detail" view when the user expands the record result. But the detection part of the problem might be the same type of problem on the UI side...

**Comment by twelch** [comment]
Approach I'm seeing is to try and pull all origin attributes and aggregate them somehow so they don't take up a ton of room.  What would be appropriate @fishytodd @tchaddad @cybersea?  One idea is to combine into a single string like:

Van C. Hare, National Fish Habitat Partnership, Pacific Marine and Estuarine Fish Habitat Partnership, United States Geological Survey

**Comment by cybersea** [comment]
That sounds like a good approach to me.  You might need a semi-colon (or maybe a pipe?) instead of a comma because often a single originator can have a bunch of commas in it.    See, for example:  http://wcga-vm01.sdsc.edu/discover/#?s=Sound%20GIS%20Test&text=commercial

**Comment by tchaddad** [comment]
I was thinking something similar about more distinctive separator. But I like the idea overall (and I think originators would too).

**Comment by twelch** [comment]
Okay, currently the attribute fetching is naive.  If a selector returns multiple values from the document it simply takes the first.  My plan would be to make this more robust by adding an additional handler that returns a semicolon-separated list and then specify for each attribute which handler to use, list or firstValue.

**Comment by cybersea** [comment]
That sounds great.  Would it apply to any of the attributes?  Like publisher, distributor, email contact, etc.?

**Comment by tchaddad** [comment]
That means that this fix will affect other fields with possible multiple values?

**Comment by twelch** [comment]
I would set it up so that you have the control over each.  Initially fgdc/creator would be configured to create a 'list' while the rest continue to use 'first'.  Others could be switched over to list as needed, as long as a selector or selectors can be written that return the desired values.  So some work would be needed for each to get it right.  I need to play with this a bit but I think it will work.  Here's an example of the 'enhanced' Metadata.js paths config:

```
creator: {
  fgdc: {
    selector: "metadata > idinfo > citation > citeinfo > origin",
    display: "list"
  },
  iso: {
    selector: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:pointOfContact > gmd\\:CI_ResponsibleParty > gmd\\:organisationName > gco\\:CharacterString, identificationInfo > MD_DataIdentification > pointOfContact > CI_ResponsibleParty > organisationName > CharacterString",
    display: "first"
  }
},
publisher: {
  ...
}
```
