### ISSUE TITLE
Update to new geoportal

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#39]
upgrade to new geoportal instance

consult with Christine white about the new upgrades to understand if other aspects of portal will break. 

should be schedule for late july to incorporate new updates

**Comment by tchaddad** [comment]
Slight correction - I think any new Geoportal upgrades will be available in later July, meaning this work should be scheduled in August-ish...

**Comment by tchaddad** [comment]
Closing in favor of the more current upgrade tickets.
