### ISSUE TITLE
Two Zip file links pointing to same URL

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#40]
Found a few cases where there are two ZIP links showing for a record.   This would be great if they were different zip files, but in this case, they are the same file, but the link is provided in two different places in the metadata.

It's FGDC metadata and the links are located in both onlink and stdorder->digform->digtopt->onlinopt

Examples:
http://portal.westcoastoceans.org/discover/#?text=Pore_shore
http://portal.westcoastoceans.org/discover/#?text=Farallones%2010m

**Comment by tchaddad** [comment]
Unfortunately this is not really a bug... the code is successfully looking at all the XPaths we tell it to look in, and correctly labeling what it finds.

But we can think on how to make it better...

**Comment by cybersea** [comment]
Understood -- I was looking for a label to indicate this was low priority.  I just wanted to make sure to document the unicorn sighting.

**Comment by tchaddad** [comment]
We can create a custom "Unicorn" label...

**Comment by emiliom** [comment]
@tchaddad, does this mean that the catalog can now list more than one link of the same link type, across the board and not just for zip files? That used to be a need way back, and I didn't realize it had been addressed.

**Comment by tchaddad** [comment]
I'm not sure we've specifically tested for this (or explicitly tried to fix for it). It's more a side effect of some groups putting links in more than one place. At least, the reason it works in the instances that I've seen is that the paths themselves are unique.Theoretically this would work for any link type (not just ZIP).

**Comment by emiliom** [comment]
Ok. Thanks.

**Comment by tchaddad** [comment]
Closing in favor of specifying that we want to know how to list more than one link of the same link type (consistently and intentionally).
