### ISSUE TITLE
Create Github Repo for Geoportal & Server Side configurations/modifications

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#46]
This was a key suggestion from our recent discussions about keeping the dev and production portal in sync.

Thought I would add it as a ticket to remind us.

**Comment by tchaddad** [comment]
Thanks for this - I'll add that as part of this we want to figure out if the repo at Ecotrust is even close to usable as a starting point for this purpose: https://github.com/Ecotrust/geoportal-server

**Comment by tchaddad** [comment]
Also, somewhat linked to https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/39

**Comment by cybersea** [comment]
Created a repo with just files that have been changed in Geoportal since the original install.   See the READ Me for description and expected workflow.

https://github.com/WCGA/wcodp_config   

I tested this out with some updates to one of the profile configuration files.  I'm happy to walk through this when folks have time.
