### ISSUE TITLE
URL Links showing on Dev portal, but not on Production

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#48]
There are some server side changes that need to be done to show some URLS.  This is working on dev, but not on production.

Compare:
http://portal.westcoastoceans.org/discover/#?s=SCCOOS  
http://wcga-vm01.sdsc.edu/discover/#?s=SCCOOS

and

http://portal.westcoastoceans.org/discover/#?text=OCNMS
http://wcga-vm01.sdsc.edu/discover/#?text=OCNMS

**Comment by tchaddad** [comment]
Possible missing XSLT paths on production (for ISO-2 metadata), ATRAC tool metadata output specifically.
