### ISSUE TITLE
Only apply "OPEN" after all other link types have been captured

### ISSUE THREAD

**Issue by tchaddad** [WCGA/West-Coast-Ocean-Data-Portal#49]
Likely new logic required on the UI side for this to work.

**Comment by tchaddad** [comment]
Or, do not display OPEN for an link already captured by a different label...

**Comment by tchaddad** [comment]
maybe a duplicate of https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/9

**Comment by twelch** [comment]
@tchaddad or @fishytodd what is an example of a record with the described behavior of both an OPEN and other link with the same URL?  Please provide URL, thanks.

**Comment by fishytodd** [comment]
I believe that the goal of this issue ticket is to provide a link type that
would recognize websites that are included in the metadata record for
things like data download webpages, or organizational websites.

There seemed to be too much variation to do this correctly without also
triggering things like service URLs.

Here is one where Open is currently being applied -
http://portal.westcoastoceans.org/geoportal/rest/document?id={569BC041-9369-4DE6-9346-A8AE677B8594}

Here is one where it isn't but could be to open up the Otter Labs link
http://portal.westcoastoceans.org/geoportal/rest/document?id={484F1B76-96E5-49E1-B75A-8BFBDE47AB3B}
http://portal.westcoastoceans.org/geoportal/rest/document?id={484F1B76-96E5-49E1-B75A-8BFBDE47AB3B}

Would be nice if the Open link captured the .aspx link in the record below

http://portal.westcoastoceans.org/geoportal/rest/document?id={683E3EF7-18C7-4BE1-97C9-30BDAB5CBEBE}

On Mon, Sep 21, 2015 at 3:08 PM, Tim Welch notifications@github.com wrote:

> @tchaddad https://github.com/tchaddad or @fishytodd
> https://github.com/fishytodd what is an example of a record with the
> described behavior of both an OPEN and other link with the same URL? Please
> provide URL, thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/49#issuecomment-142124006
> .

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by tchaddad** [comment]
Closing in favor of #9
