### ISSUE TITLE
Modify Use Case "Uncertaintly Language" on homepage and marine debris page

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#5]
Language should be added to provide a bit more information about uncertainty of marine debris database. Possible places include homepage, inform page, and marine debris page.

**Comment by tchaddad** [comment]
Can we get more detail here? I don't know enough about what this is referring to to make any informed comments.

**Comment by fishytodd** [comment]
Homepage text should read "View marine debris composition and distribution"
