### ISSUE TITLE
Production SOLR issues

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#54]
Portal.westcoastoceans.org/SOLR logging shows several warnings: 

null:ClientAbortException: java.net.SocketException: Broken pipe

null:java.lang.NumberFormatException: multiple points

org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse

![image](https://cloud.githubusercontent.com/assets/5833896/13884869/28e64828-eced-11e5-9aac-99160e8ed5e2.png)

Might be related to memory loss issues, search bar optimization, or periodic need to restart tomcat and ubuntu.

**Comment by tchaddad** [comment]
@cybersea I would guess that this Issue is closable since it references the Production server. Would you agree?

**Comment by cybersea** [comment]
Ok with me.  We can re-open if needed
