### ISSUE TITLE
Production portal periodically shows 0 records

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#55]
Possibly related to SOLR issues described in Issue 54 https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/54

Every 2 weeks or so, Portal UI shows 0 records. Restarting tomcat and ubuntu servers usually resolves issue for 2 weeks.

**Comment by tchaddad** [comment]
May not be relevant anymore
