### ISSUE TITLE
Development Server SOLR issues

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#56]
Similar issues to #54 development (207.141.116.172/SOLR) gives several severe warnings. Problem seems to be preventing from Dev SOLR index from being rebuilt, which also prevents ability to test viewing of harvested records in dev UI. 

SolrIndexWriter was not closed prior to finalize(),​ indicates a bug -- POSSIBLE RESOURCE LEAK!!!

Error closing IndexWriter,​ trying rollback

org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/usr/local/apps/solr/collection1/data/index/write.lock: java.io.FileNotFoundException: /usr/local/apps/solr/collection1/data/index/write.lock (Permission denied)

![image](https://cloud.githubusercontent.com/assets/5833896/13885267/c5372fac-ecee-11e5-93ac-e96271b938ea.png)

**Comment by cybersea** [comment]
Paul Smith at SCCWRP found some permission differences between the DEV and PROD portal.

He did made the following changes:
Changed: /usr/local/apps/solr/collection1/data/index
From: wcga.wcga
To: tomcat.root

Changed: /usr/local/apps/solr/collection1/data/index/*
From: wcga.wcga
To: tomcat.tomcat

**Comment by cybersea** [comment]
Still seem to be having issues with the daily automated solr reindexing.  
Reloading solr from Tomcat Manager UI does not seem to do the trick (on DEV or PROD)

Am able to reindex manually using 
`service tomcat6 restart`

**Comment by tchaddad** [comment]
May not be relevant anymore
