### ISSUE TITLE
Export data catalogs contents

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#6]
Interest in exporting entire catalog in a useful format (CSV?). From Network meeting. Ned Bader IBM suggested.

**Comment by tchaddad** [comment]
This hinges on the definition of "useful" - I think the results of any selection are already available as JSON, but maybe a more prominent link to a dump would be an easy way to satisfy this.

**Comment by tchaddad** [comment]
This is already possible with the CSW endpoint:

http://portal.westcoastoceans.org/geoportal//csw?service=CSW&version=2.0.2&request=GetRecords

You can add different options to the end of this URL to get the records back in a number of different formats.
