### ISSUE TITLE
Problems harvesting of NAP records from Canadian portal

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#61]
Some possible resources:

ftp://ftp.ncddc.noaa.gov/pub/Metadata/Online_ISO_Training/Intro_to_ISO/handouts/Comparison_between_NAP_and_ISO.pdf

[nap.zip](https://github.com/WCGA/West-Coast-Ocean-Data-Portal/files/332400/nap.zip)

**Comment by tchaddad** [comment]
NAP turned out not to be the problem here. Rather, we had a 19115 validation rule set too strictly, which was blocking validation from this source. 

Solved here: https://github.com/WCGA/wcodp_config/commit/2a1b097bbb0671ea475b47ea54f477df9ec7cfb3
