### ISSUE TITLE
MapQuest tiles discontinued

### ISSUE THREAD

**Issue by tchaddad** [WCGA/West-Coast-Ocean-Data-Portal#64]
need to replace with another tile source. change needs to be made on ubuntu in:

`site_raw/_includes/js/directives/Filters.js`

will also require `grunt compress` afterwards to rebuild all.js, and then testing with `jekyll serve` before committing.

**Comment by tchaddad** [comment]
@cybersea this is now fixed on Dev if you want to check it out and confirm, I will put it on Prod was well.

**Comment by cybersea** [comment]
Nice work.  Thanks for fixing that. 

Wondering if you could put the links to the commits here so we can reference what needed to be done for the future.

Also, I noticed the changes are in the master branch.  Probably want to pull them into the dev branch as well to keep things consistent.

**Comment by tchaddad** [comment]
I think the last commit is the most relevant: https://github.com/Ecotrust/wc-data-registry/commit/2fd68c4fa2400ddb8adf768bdb564973b4f57807

**Comment by tchaddad** [comment]
Should be all in sync now, and changes are on Prod.
