### ISSUE TITLE
Move WCODP to https

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#67]
We probably need to transition the site to https.   Discuss what this would entail and the level of effort.  There are numerous reasons to do this, but embedding our site in an ESRI story map is one of them:

https://blogs.esri.com/esri/arcgis/2017/06/06/web-security-and-story-maps/

**Comment by tchaddad** [comment]
We will have to purchase a certificate, and then install.

**Comment by tchaddad** [comment]
Done
