### ISSUE TITLE
Install security patch for Geoportal

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#69]
https://blogs.esri.com/esri/arcgis/2017/01/28/open-source-geoportal-server-security-patch/

Note that this requires upgrading to v.1.2.7

**Comment by cybersea** [comment]
We are upgrading to v.1.2.9, so this security issue will be handled with that upgrade

**Comment by tchaddad** [comment]
We are now upgraded.
