### ISSUE TITLE
Refer to different metadata field (for ISO-2 constraints)

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#8]
The paths in the UI may not be referencing the correct location in ISO 19115-2 records. A couple of attempts have been made - will know more after Emilio has a chance to look on 1/7/2015.

Ecotrust/wc-data-registry#122

**Comment by tchaddad** [comment]
Closing this issue. All hail @emiliom !

**Comment by fishytodd** [comment]
refers to files metadata.js

**Comment by tchaddad** [comment]
The final edits to Metadata.js were as follows:

for datePublished:

> ```
>   isoii: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:citation > gmd\\:CI_Citation > gmd\\:date > gmd\\:CI_Date > gmd\\:date > gco\\:Date, identificationInfo > MD_DataIdentification > citation > CI_Citation > date > CI_Date > gdate > Date"
> ```

for creator:

> ```
>  isoii: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:citation > gmd\\:CI_Citation > gmd\\:citedResponsibleParty > gmd\\:CI_ResponsibleParty > gmd\\:organisationName > gco\\:CharacterString, identificationInfo > MD_DataIdentification > gcitation > CI_Citation > citedResponsibleParty > CI_ResponsibleParty > organisationName > CharacterString"
> ```

for publisher:

> ```
>  isoii: "gmd\\:contact > gmd\\:CI_ResponsibleParty > gmd\\:organisationName > gco\\:CharacterString, contact > CI_ResponsibleParty > organisationName > CharacterString"
> ```

for contact name:

> ```
>   isoii: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:citation > gmd\\:CI_Citation > gmd\\:citedResponsibleParty > gmd\\:CI_ResponsibleParty > gmd\\:individualName, identificationInfo > MD_DataIdentification > citation > CI_Citation > citedResponsibleParty > CI_ResponsibleParty > individualName"
> ```

for contact email:

> ```
>  isoii: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:citation > gmd\\:CI_Citation > gmd\\:citedResponsibleParty > gmd\\:CI_ResponsibleParty > gmd\\:contactInfo > gmd\\:CI_Contact > gmd\\:address > gmd\\:CI_Address > gmd\\:electronicMailAddress > gco\\:CharacterString, identificationInfo > MD_DataIdentification > citation > CI_Citation > citedResponsibleParty > CI_ResponsibleParty > gmd\\:contactInfo > CI_Contact > address > CI_Address > electronicMailAddress > CharacterString"
> ```

for constraints:

> ```
>   isoii: "gmd\\:identificationInfo > gmd\\:MD_DataIdentification > gmd\\:resourceConstraints > gmd\\:MD_LegalConstraints > gmd\\:useLimitation > gco\\:CharacterString, identificationInfo > MD_DataIdentification > resourceConstraints > MD_LegalConstraints > useLimitation > CharacterString"
> ```

**Comment by emiliom** [comment]
@tchaddad, I'm curious: Is this simply listing what we/I modified on Metadata.js on the dev server early this month, or is it new, additional changes to address other issues? If it's the latter, can you describe the new issues very briefly?

I'm going to mention issue #33 here, just so the linkage that Tanya mentioned over email is also present on the github issues, for reference.

**Comment by tchaddad** [comment]
This is nothing new Emilio - it's just that Jenny pointed out that the actual solution was not linked to the GitHub issue directly, so I decided to add it before closing the ticket. It is unrelated to issue #33 except to say that if #33 is not pushed to the server, than the UI cannot access the metadata in order to read the XPaths.

So, 2 separate issues, either one blocking viewing of your attributes.

**Comment by emiliom** [comment]
Thanks!
